import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans} from "next/font/google";
import "./globals.css";
import AppWrapper from "@/components/AppWrapper";
import AuthProvider from "@/components/AuthProvider";
import Header from "@/components/Header";
const poppins = Nunito_Sans({ subsets: ['latin'], weight: ['400', '700'] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins} antialiased`}
      >

        <AuthProvider>
        <AppWrapper>
          <div className="min-h-screen text-black bg-gradient-to-br from-yellow-100 to-red-100 px-6 py-10">
          <Header/>
          {children}
          </div>
        </AppWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
